### ISSUE TITLE
Create simple README

### ISSUE THREAD

**Issue by kramerbastian** [kramerbastian/tascli#4]
For now, just put descriptions of commands from the `--help` command in README and provide a simple introduction to the tool with installation instructions (deno.land/x). You can use the Design below.

![preview](https://user-images.githubusercontent.com/61729645/195907328-446cc3ad-58c8-487c-89a5-941c213ce82f.png)

**Comment by S-Parker7000** [comment]
I am on it

**Comment by gunjansaha55** [comment]
Please assigned me in this issue I am beginner.

**Comment by kramerbastian** [comment]
Sure!
